### ISSUE TITLE
Conversion of intf to int, float and double

### ISSUE THREAD

**Issue by zhongjingjogy** [AlyShmahell/polymath#1]
Hi AlyShmahell,

I wonder if it is possible to add an interface for converting intf to integer or float number?

Best regards,

Jing

**Comment by zhongjingjogy** [comment]
I would like to add some more details for the issue.
1. Do the conversion
```
    intf a = 400;
    double v = a;
    double v1 = int(a);
```
2. Compile it (with C++11)

Errors are encountered, i.e.,
```
main.cpp:9:16: error: cannot convert 'intf' to 'double' in initialization
     double v = a;
                ^
main.cpp:10:22: error: invalid cast from type 'intf' to type 'int'
     double v1 = int(a);
                      ^
```

**Comment by zhongjingjogy** [comment]
A potential solution is to add cast-operator, i.e.,
```
class intf {
     // other member functions
    operator int() const;
    operator double() const;
};

inline intf::operator int() const {
  int v = 0;
  int scale = 1;
  for (auto it = digits.rbegin(); it != digits.rend(); ++it) {
    v += scale * *it;
    scale *= 10;
  }
  return v;
}

inline intf::operator double() const {
  double v = 0;
  double scale = 1.0;
  for (auto it = digits.rbegin(); it != digits.rend(); ++it) {
    v += scale * *it;
    scale *= 10.0;
  }
  return v;
}
```

**Comment by AlyShmahell** [comment]
@zhongjingjogy 
Hello, and thank you for pointing this out.
cast operators have been added, please check example_3.cpp, it also covers exception handling in case intf is of bigger size than int, (last two lines of code).

**Comment by zhongjingjogy** [comment]
That is great! I am considering of using intf as the hash value for my application. Thank you so much for your work.

P.S. The indentation of the code is not consistent. I would like to recommend clang-format to you, which is a very nice tool for formatting C++ codes.

**Comment by AlyShmahell** [comment]
@zhongjingjogy 
So far I've been using the default A-Style in codeblocks, but I will give clang-format a try during the next update, so thank you.
I'm also going to add primality testing to the library, specifically "Atkin–Morain", if you are interested in that I would appreciate the help 😃
